AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mongodb-Serverless-V1

  Sample SAM Template for mongodb-Serverless-V1
  
Globals:
  Function:
    Timeout: 600  # 10 minutes in seconds

Resources:
  # MongodbServerlessV1Role:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Action: "sts:AssumeRole"
  #           Principal:
  #             Service: "lambda.amazonaws.com"
  #     Policies:
  #       - PolicyName: "MongodbServerlessV1SecretsManagerPolicy"
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             - Effect: "Allow"
  #               Action:
  #                 - "secretsmanager:GetSecretValue"
  #               Resource: "arn:aws:secretsmanager:ap-south-1:115305147291:secret:lqs/apiKey-*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "secretsmanager:DescribeSecret"
  #               Resource: "arn:aws:secretsmanager:ap-south-1:115305147291:secret:lqs/apiKey-*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "s3:*"
  #               Resource: "*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "lambda:*"
  #               Resource: "*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "cloudformation:*"
  #               Resource: "*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "logs:*"
  #               Resource: "arn:aws:logs:*:*:*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "sqs:*"
  #               Resource: "*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "sns:*"
  #               Resource: "*"

  MongodbServerlessV1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 512  # 512 MB memory for the Lambda function
      Timeout: 600     # 10 minutes timeout
      Policies:
        - AmazonS3FullAccess  # Full access to S3
        - SecretsManagerReadWrite  # Full access to Secrets Manager
        - AWSLambda_FullAccess  # Full access to Lambda resources
        - AmazonSQSFullAccess   # Full access to SQS
        - AmazonSESFullAccess   # Full access to SES

      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
            Input: '{"lob": "1"}'

Outputs:
  MongodbServerlessV1Name:
    Description: The name of the MongodbServerlessV1 Lambda function
    Value: !Ref MongodbServerlessV1
  MongodbServerlessV1Arn:
    Description: The ARN of the MongodbServerlessV1 Lambda function
    Value: !GetAtt MongodbServerlessV1.Arn